In [6]:
%pip install h2o

Requirement already satisfied: h2o in /Users/simenvoldqvam/Library/Python/3.10/lib/python/site-packages (3.38.0.2)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/site-packages (from h2o) (0.9.0)
Requirement already satisfied: future in /usr/local/lib/python3.10/site-packages (from h2o) (0.18.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from h2o) (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/site-packages (from requests->h2o) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->h2o) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->h2o) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->h2o) (2022.6.15.1)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn
from sklearn import svm, preprocessing
from sklearn.impute import SimpleImputer
import h2o
from h2o.automl import H2OAutoML

In [8]:
h2o.init(ip="localhost", port="54321")

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.10" 2021-01-19; OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9); OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
  Starting server from /Users/simenvoldqvam/Library/Python/3.10/lib/python/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /var/folders/z4/blr9pbks7g1gwx7yzstbjlgw0000gn/T/tmpkjilhcnr
  JVM stdout: /var/folders/z4/blr9pbks7g1gwx7yzstbjlgw0000gn/T/tmpkjilhcnr/h2o_simenvoldqvam_started_from_python.out
  JVM stderr: /var/folders/z4/blr9pbks7g1gwx7yzstbjlgw0000gn/T/tmpkjilhcnr/h2o_simenvoldqvam_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Europe/Oslo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.38.0.2
H2O_cluster_version_age:    6 days
H2O_cluster_name:           H2O_from_python_simenvoldqvam_8zkqps
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.6 final
--------------------------  ------------------------------------

In [9]:
#train_df = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/dataset_train_without_rev_features.csv")
#test_df = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/dataset_test_without_rev_features.csv")

#train_df2 = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/dataset_train_with_stores_extra.csv")
test_df2 = h2o.import_file("/Users/simenvoldqvam/Desktop/Skole/machine_learning/data/train_data/dataset_test_2.csv")

test_train = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/test_train.csv")
test_test = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/test_test.csv")
rev_labels = h2o.import_file("C:/Users/aminp/OneDrive/Dokumenter/NTNU/4år/Machinelearning/machine_learning/data/train_data/revenue_labels.csv")

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [106]:
#x_train = test_train.drop([0], axis = 0)

#y_test = test_test.drop([0], axis = 0 )

rev = rev_labels[:, 1]

x_train = test_train.cbind(rev)

list_df = ["C1", "mall_is", "geo__Cluster 4 similarity", "geo__Cluster 6 similarity",
 "geo__Cluster 7 similarity","geo__Cluster 0 similarity", "geo__Cluster 1 similarity", 
 "geo__Cluster 2 similarity", "geo__Cluster 3 similarity", "geo__Cluster 5 similarity", "geo__Cluster 8 similarity" ]

x_train2 = x_train.drop(["C1", "mall__is", "geo__Cluster 0 similarity", "geo__Cluster 1 similarity",
 "geo__Cluster 2 similarity","geo__Cluster 3 similarity", "geo__Cluster 4 similarity", 
 "geo__Cluster 5 similarity", "geo__Cluster 6 similarity", "geo__Cluster 7 similarity", "geo__Cluster 8 similarity", "geo__Cluster 9 similarity"], axis = 1)

y_test1 = test_test.drop("C1", axis = 1)

test_df3 = test_df2.drop([0], axis =0)

test_df4 = test_df3[:, 0]

y_test = test_df4.cbind(y_test1)



x_train2

  chain__is    mall___avg_revenue    chain___avg_revenue    stores_gk_lv1__store_count    stores_gk_lv1_extra__store_count    rev_stores_gk_lv1__avg_revenue    rev_stores_lv4__avg_revenue    revenue
-----------  --------------------  ---------------------  ----------------------------  ----------------------------------  --------------------------------  -----------------------------  ---------
          1               3.5277                23.6423                             20                                  17                          10.3302                          10.341     17.998
          1             nan                     23.6423                             37                                  47                          11.2428                          10.341     23.828
          1               8.0577                 7.01355                             4                                   4                           7.38225                         10.341     16.099
          1               6.64067                7.01355                            14                                  16                           8.67571                         10.341      9.296
          1               3.831                  7.01355                             5                                   9                          10.011                           10.341      4.528
          1             nan                      7.01355                            26                                  16                           9.84212                         10.341     12.02
          1               6.03871                7.01355                             1                                   4                           7.622                           10.341      7.622
          0             nan                    nan                                   8                                  13                           4.902                           10.341      3.64
          1               8.40589               23.6423                              3                                  10                          15.306                           10.341     30.514
          1             nan                      5.737                               1                                   1                           6.339                           10.341      6.339
[12859 rows x 8 columns]

In [108]:
x = x_train2.columns
y = 'revenue'
x.remove(y)

aml = H2OAutoML(max_models=10, seed=1)
aml.train(x=x, y=y, training_frame= x_train2)

AutoML progress: |█
11:03:12.933: AutoML: XGBoost is not available; skipping it.

██████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_BestOfFamily_1_AutoML_10_20221103_110312

No summary for this model

ModelMetricsRegressionGLM: stackedensemble
** Reported on train data. **

MSE: 33.210809877356816
RMSE: 5.762882080813108
MAE: 2.777619062558034
RMSLE: 0.5669417238165082
Mean Residual Deviance: 33.210809877356816
R^2: 0.8574951641613888
Null degrees of freedom: 10048
Residual degrees of freedom: 10045
Null deviance: 2342003.667668871
Residual deviance: 333735.4284575586
AIC: 63728.221752430494

ModelMetricsRegressionGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 55.27285960286772
RMSE: 7.43457191792962
MAE: 3.3160764064019217
RMSLE: NaN
Mean Residual Deviance: 55.27285960286772
R^2: 0.7662265909500454
Null degrees of freedom: 12858
Residual degrees of freedom: 12854
Null deviance: 3041097.1904217396
Residual deviance: 710753.701633276
AIC: 88098.19547733795

Cross-Validation Metrics Summary:
                        mean      sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  --------  ---------  ------------  ------------  ------------  ------------  ------------
mae                     3.32008   0.203526   3.49348       3.35905       3.14478       3.52814       3.07496
mean_residual_deviance  55.2118   9.69002    53.1801       46.2017       54.1425       71.6547       50.88
mse                     55.2118   9.69002    53.1801       46.2017       54.1425       71.6547       50.88
null_deviance           608219    90731      542212        513422        654938        739068        591458
r2                      0.766356  0.0203045  0.74281       0.767187      0.783327      0.74936       0.789096
residual_deviance       142075    25790.5    139438        119431        141907        184941        124656
rmse                    7.40915   0.628807   7.29247       6.79718       7.35816       8.46491       7.13302
rmsle                   0.620568  0.0147326  nan           0.631794      0.601159      0.632241      0.61708

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [109]:

lb = h2o.automl.get_leaderboard(aml, extra_columns = "ALL")
best_model = aml.get_best_model()

lb

model_id                                                     rmse      mse      mae       rmsle    mean_residual_deviance  algo
--------------------------------------------------------  -------  -------  -------  ----------  ------------------------  ---------------
StackedEnsemble_BestOfFamily_1_AutoML_10_20221103_110312  7.43457  55.2729  3.31608  nan                          55.2729  StackedEnsemble
StackedEnsemble_AllModels_1_AutoML_10_20221103_110312     7.46106  55.6674  3.30704    0.616933                   55.6674  StackedEnsemble
GBM_2_AutoML_10_20221103_110312                           7.46898  55.7857  3.30829  nan                          55.7857  GBM
GBM_4_AutoML_10_20221103_110312                           7.53     56.7009  3.31474  nan                          56.7009  GBM
GBM_3_AutoML_10_20221103_110312                           7.5428   56.8938  3.28735  nan                          56.8938  GBM
GBM_5_AutoML_10_20221103_110312                           7.67271  58.8704  3.39834  nan                          58.8704  GBM
DRF_1_AutoML_10_20221103_110312                           7.70424  59.3554  3.31925    0.626919                   59.3554  DRF
XRT_1_AutoML_10_20221103_110312                           7.76305  60.2649  3.36544    0.62639                    60.2649  DRF
GBM_1_AutoML_10_20221103_110312                           7.92171  62.7535  3.50807  nan                          62.7535  GBM
DeepLearning_1_AutoML_10_20221103_110312                  8.01908  64.3056  3.93326  nan                          64.3056  DeepLearning
[12 rows x 7 columns]

In [104]:
m = h2o.get_model(lb[1,"model_id"])
m.varimp(use_pandas=True)

,variable,relative_importance,scaled_importance,percentage
0,chain___avg_revenue,5.787269e+06,1.000000,0.459963
1,rev_stores_gk_lv1__avg_revenue,4.031666e+06,0.696644,0.320430
2,rev_stores_lv4__avg_revenue,1.318110e+06,0.227760,0.104761
3,stores_gk_lv1__store_count,6.656607e+05,0.115022,0.052906
4,stores_gk_lv1_extra__store_count,2.625968e+05,0.045375,0.020871
5,mall___avg_revenue,2.334124e+05,0.040332,0.018551
6,geo__Cluster 9 similarity,2.247392e+05,0.038833,0.017862
7,chain__is,5.858143e+04,0.010122,0.004656

In [105]:
#model = h2o.get_model(lb[2,"model_id"])
prediction = aml.leader.predict(y_test)
df = y_test.cbind(prediction)
df = df.as_data_frame(use_pandas=True)
result = df.loc[:,("store_id", 'predict')]
submission = result.rename(columns = {"store_id": "id",  "predict" : "predicted"})
submission.to_csv("StackedEnsembleBestOfFamily.csv", index = False)

submission

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

                              id  predicted
0     914206820-914239427-717245   4.456851
1     916789157-916823770-824309   4.610909
2       913341082-977479363-2948   2.558722
3      889682582-889697172-28720   4.062493
4     997991699-998006945-417222  25.578228
...                          ...        ...
8572  917323003-917383529-844309   8.825647
8573  917353379-917411824-845904   2.923221
8574  917072302-917089248-833647  33.390177
8575  916960557-916993161-829908  27.035976
8576   987280891-972040746-45320   6.517988

[8577 rows x 2 columns]